baseURL = "https://aborroy.github.io/alfresco-marketplace/"
languageCode = "en-us"
title = "Alfresco Marketplace"
paginate = 24

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"

[outputs]
home = ["HTML", "JSON"]
