name: "Submit a catalog entry"
description: "Use this form to propose a new listing. A PR will be created for review."
title: "[Catalog Entry] "
labels: ["new-entry"]
body:
  - type: input
    id: title
    attributes:
      label: "Name"
      placeholder: "Alfresco Add-on for X"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Description (short)"
      description: "Short overview and links to docs."
    validations:
      required: true

  - type: checkboxes
    id: compatibility
    attributes:
      label: "Compatibility"
      description: "Select the Alfresco versions this applies to"
      options:
        - label: "ACS 4.x"
        - label: "ACS 5.x"
        - label: "ACS 6.x"
        - label: "ACS 7.x"
        - label: "ACS 23.1"
        - label: "ACS 23.2"
        - label: "ACS 23.3"
        - label: "ACS 23.4"
        - label: "ACS 23.x"
        - label: "ACS 25.1"
        - label: "ACS 25.2"
        - label: "ACS 25.x"

  - type: dropdown
    id: license
    attributes:
      label: "License"
      description: "Pick the license from these SPDX standard IDs"
      options:
        - Apache-2.0
        - MIT
        - BSD-3-Clause
        - GPL-2.0-or-later
        - GPL-3.0-or-later
        - LGPL-3.0-or-later
        - LicenseRef-Proprietary
        - LicenseRef-Public-Domain
    validations:
      required: true

  - type: input
    id: keywords
    attributes:
      label: "Keywords (comma-separated, lowercase)"

  - type: input
    id: download_url
    attributes:
      label: "Download page link (URL)"

  - type: input
    id: vendor
    attributes:
      label: "Author/Vendor name"

  - type: dropdown
    id: vendor_type
    attributes:
      label: "Contributor type"
      description: "Select who is contributing this entry"
      options:
        - partner
        - customer
        - community
    validations:
      required: true

  - type: input
    id: about_url
    attributes:
      label: "About URL"

  - type: textarea
    id: about
    attributes:
      label: "About"

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots (one URL per line)"

  - type: textarea
    id: notes
    attributes:
      label: "Notes to reviewers (optional)"
      description: "Anything we should know."
